import { useEffect, useState } from "react";
import { AlertCircle, BarChart3, Download, Filter, Mail, Plus, Search, Share2, Users } from "lucide-react";
import { mentorshipAPI } from "../../services/api";

const emptyStats = { totalMentors: 0, totalMentees: 0, awaitingFeedback: 0, awaitingResponse: 0, upcomingSessions: 0, completedSessions: 0, newProfiles: 0, totalSessions: 0 };
const labelMap = { awaiting_response: "Waiting for mentee to confirm", awaiting_feedback: "Waiting for feedback", upcoming: "Upcoming session", completed: "Session completed", cancelled: "Session cancelled" };

const MentorshipTab = ({ onError, onOpenMail }) => {
  const [view, setView] = useState("analytics");
  const [stats, setStats] = useState(emptyStats);
  const [profiles, setProfiles] = useState([]);
  const [sessions, setSessions] = useState([]);
  const [search, setSearch] = useState("");
  const [loading, setLoading] = useState(true);

  const load = async () => {
    setLoading(true);
    try {
      const [dashboard, sessionResponse] = await Promise.all([mentorshipAPI.getDashboard(), mentorshipAPI.getSessions()]);
      setStats({ ...emptyStats, ...(dashboard.data.stats || {}) });
      setSessions(sessionResponse.data.sessions || []);
      if (view === "mentors" || view === "mentees") {
        const response = await mentorshipAPI.getProfiles({ type: view === "mentors" ? "mentor" : "mentee", search });
        setProfiles(response.data.profiles || []);
      }
    } catch (error) { onError(error.response?.data?.message || "Unable to load mentorship data"); } finally { setLoading(false); }
  };
  useEffect(() => { load(); }, [view, search]);

  const tabs = [["analytics", "Analytics", BarChart3], ["promote", "Promote Mentorship", Share2], ["mentors", "View Mentors List", Users], ["mentees", "View Mentees List", Users]];
  if (loading) return <div className="border border-slate-200 bg-white p-12 text-center text-slate-500">Loading mentorship workspace...</div>;

  return <div className="space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3 bg-[#344579] px-6 py-4 text-white"><div><p className="text-xs uppercase tracking-[0.2em] text-blue-100">Admin Area</p><h2 className="mt-1 text-xl font-semibold">Flash Mentorship</h2></div><button onClick={load} className="border border-white/30 px-4 py-2 text-sm">Refresh</button></div>
    <div className="grid grid-cols-2 gap-1 border border-slate-200 bg-white md:grid-cols-4">{tabs.map(([key, label, Icon]) => <button key={key} onClick={() => setView(key)} className={`flex items-center justify-center gap-2 border-b-2 px-3 py-4 text-sm ${view === key ? "border-[#176fc1] text-[#176fc1]" : "border-transparent text-slate-600"}`}><Icon size={16} />{label}</button>)}</div>

    {view === "analytics" && <div className="space-y-6"><div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Total Mentors", stats.totalMentors, "View mentors", "mentors"], ["Total Mentees", stats.totalMentees, "View mentees", "mentees"], ["Sessions Awaiting Feedback", stats.awaitingFeedback, "View sessions", "sessions"], ["Sessions Awaiting Response", stats.awaitingResponse, "View sessions", "sessions"]].map(([label, value, action, target]) => <div key={label} className="border border-slate-200 bg-white p-5"><p className="text-sm text-slate-600">{label}</p><p className="mt-2 text-3xl font-semibold text-slate-900">{value}</p><button onClick={() => setView(target)} className="mt-6 border border-slate-300 px-4 py-2 text-sm text-slate-700">{action}</button></div>)}</div><div><h3 className="mb-4 text-2xl font-semibold text-slate-900">Important Actions</h3><div className="grid gap-4 md:grid-cols-3"><div className="bg-sky-200 p-6"><AlertCircle size={18} /><h4 className="mt-4 font-semibold">Very few mentorship requests in recent time</h4><p className="mt-3 text-sm text-slate-600">Promote the mentorship platform regularly to encourage members to connect.</p><button onClick={() => setView("promote")} className="mt-5 bg-[#176fc1] px-4 py-2 text-sm font-semibold text-white">Promote Mentorship</button></div><div className="bg-orange-200 p-6"><AlertCircle size={18} /><h4 className="mt-4 font-semibold">Sessions booking rate is low</h4><p className="mt-3 text-sm text-slate-600">Review the session table and follow up with participants.</p><button onClick={() => setView("sessions")} className="mt-5 bg-[#176fc1] px-4 py-2 text-sm font-semibold text-white">Session Table</button></div><div className="bg-amber-200 p-6"><AlertCircle size={18} /><h4 className="mt-4 font-semibold">{stats.newProfiles === 0 ? "No new mentor or mentee in last 30 days" : `${stats.newProfiles} new profiles in last 30 days`}</h4><p className="mt-3 text-sm text-slate-600">Promote mentorship to grow active participation.</p><button onClick={() => onOpenMail("mentorship")} className="mt-5 bg-[#176fc1] px-4 py-2 text-sm font-semibold text-white">Send Mail</button></div></div></div></div>}

    {view === "promote" && <div className="space-y-5"><div className="text-center"><h3 className="text-2xl font-semibold">Promote Mentorship</h3><p className="mx-auto mt-2 max-w-2xl text-slate-600">Use dynamic mail templates and sharing actions to grow the mentorship network.</p></div><div className="grid gap-5 md:grid-cols-3"><div className="bg-sky-200 p-6"><h4 className="text-xl font-semibold">Introduce the mentorship platform to everyone.</h4><p className="mt-6 text-sm text-slate-600">Invite seniors to volunteer as mentors, then introduce mentorship to the wider alumni community.</p><div className="mt-6 flex flex-wrap gap-3"><button onClick={() => onOpenMail("mentor")} className="bg-[#176fc1] px-4 py-2 text-sm font-semibold text-white">Invite Mentors</button><button onClick={() => onOpenMail("mentee")} className="bg-[#176fc1] px-4 py-2 text-sm font-semibold text-white">Invite Mentees</button></div></div><div className="bg-amber-200 p-6"><h4 className="text-xl font-semibold">Mail templates to attract more mentors.</h4><p className="mt-6 text-sm text-slate-600">Use when the program has just started or mentor activity is low.</p><button onClick={() => onOpenMail("mentor")} className="mt-10 bg-[#176fc1] px-4 py-2 text-sm font-semibold text-white"><Mail size={15} className="mr-2 inline" />Send Mail</button></div><div className="bg-sky-300 p-6"><h4 className="text-xl font-semibold">Mail templates and banners to attract more mentees.</h4><p className="mt-6 text-sm text-slate-600">Use after a new batch joins or session activity slows down.</p><button onClick={() => onOpenMail("mentee")} className="mt-10 bg-[#176fc1] px-4 py-2 text-sm font-semibold text-white"><Mail size={15} className="mr-2 inline" />Send Mail</button></div></div><div className="bg-slate-800 p-6 text-white"><h4 className="flex items-center gap-3 text-xl font-semibold"><Share2 size={20} /> Share on Social media</h4><p className="mt-3 text-slate-300">Use your configured mentorship campaign links across social channels.</p></div></div>}

    {(view === "mentors" || view === "mentees") && <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="text-xl font-semibold">{view === "mentors" ? "Top Mentors for you" : "Mentees List"}</h3><div className="flex gap-2"><button onClick={() => onOpenMail(view === "mentors" ? "mentor" : "mentee")} className="border border-slate-300 px-4 py-2 text-sm"><Mail size={15} className="mr-2 inline" />Send Mail</button><button className="bg-[#344579] px-4 py-2 text-sm text-white"><Download size={15} className="mr-2 inline" />Download</button></div></div><div className="flex gap-2"><div className="flex border border-slate-300"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search by keyword" className="w-64 px-3 py-2 text-sm outline-none" /><Search className="m-2 text-[#344579]" size={18} /></div><button className="border border-slate-300 px-4 py-2 text-sm"><Filter size={15} className="mr-2 inline" />Filters</button></div><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{profiles.map((profile) => <div key={profile._id} className="border border-slate-200 bg-white p-6 text-center"><div className="mx-auto flex h-28 w-28 items-center justify-center rounded-full bg-[#f1c2aa] text-3xl text-[#753511]">{profile.alumniId?.firstName?.[0]}{profile.alumniId?.lastName?.[0]}</div><h4 className="mt-5 font-semibold">{profile.alumniId?.firstName} {profile.alumniId?.lastName}</h4><p className="mt-1 text-sm text-slate-600">{profile.alumniId?.jobTitle || profile.alumniId?.occupation || `Year ${profile.alumniId?.batchYear || "-"}`}</p><p className="mt-5 text-xs text-slate-500">{view === "mentors" ? "Offering Help In" : "Seeking Help For"}</p><p className="mt-2 text-sm text-slate-700">{profile.helpTopics?.join(", ") || "Career guidance and networking"}</p><button className="mt-6 w-full border border-slate-300 px-4 py-2 text-sm font-semibold">View Profile</button></div>)}</div>{profiles.length === 0 && <div className="border border-dashed border-slate-300 p-12 text-center text-slate-500">No {view} profiles have been published yet.</div>}</div>}

    {view === "sessions" && <div className="overflow-x-auto border border-slate-200 bg-white"><div className="flex items-center justify-between p-5"><h3 className="text-xl font-semibold">Session Table</h3><button className="bg-[#344579] px-4 py-2 text-sm text-white"><Plus size={15} className="mr-2 inline" />Add Session</button></div><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-slate-50 text-slate-600"><tr><th className="px-5 py-3">From (Mentee)</th><th className="px-5 py-3">To (Mentor)</th><th className="px-5 py-3">Topic(s)</th><th className="px-5 py-3">Session Date</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Feedback</th></tr></thead><tbody>{sessions.map((session) => <tr key={session._id} className="border-t border-slate-100"><td className="px-5 py-4 font-medium">{session.mentee?.firstName} {session.mentee?.lastName}<small className="block text-slate-500">Requested on: {new Date(session.requestedAt).toLocaleDateString("en-IN", { month: "short", day: "numeric", year: "numeric" })}</small></td><td className="px-5 py-4 font-medium">{session.mentor?.firstName} {session.mentor?.lastName}</td><td className="px-5 py-4">{session.topics?.join(", ") || "--"}</td><td className="px-5 py-4">{session.sessionDate ? new Date(session.sessionDate).toLocaleDateString() : "--"}</td><td className="px-5 py-4 font-medium">{labelMap[session.status] || session.status}</td><td className="px-5 py-4">{session.mentorFeedback || session.menteeFeedback || "--"}</td></tr>)}</tbody></table>{sessions.length === 0 && <p className="p-10 text-center text-slate-500">No mentorship sessions yet.</p>}</div>}
  </div>;
};
export default MentorshipTab;
